  - name: Docker | Updating dependencies...
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Docker | Adding Docker GPG Key...
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

  - name: Docker | Adding Docker Repository...
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - name: Docker | Installing Docker Packages...
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
###################################################


  - name: Docker Compose | Downloading binary file...
    shell: "curl -L 'https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64' -o /usr/local/bin/docker-compose"

  - name: Docker Compose | Permissioning binary file...
    shell: 'chmod +x /usr/local/bin/docker-compose'

  - name: Docker Compose | Creating symlink...
    shell: 'ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose'
