---
# tasks file for setupFront


  - name: Front | Cloning repository...
    git:
       repo: 'https://github.com/HenriqueLira1/SmartSearch.git'
       dest: /opt/smartsearch-app-front
       clone: yes
       force: yes
