FROM python:3.6.9
  
RUN mkdir -p /opt/smartsearch-api

RUN apt-get update -y && apt-get install libtesseract-dev tesseract-ocr poppler-utils python-pip -y

COPY . /opt/smartsearch-api

RUN cd /opt/smartsearch-api && pip install -r requirements.txt

WORKDIR /opt/smartsearch-api

EXPOSE 5000

CMD [ "python", "app.py" ]
